### ISSUE TITLE
Compatible with ROS?

### ISSUE THREAD

**Issue by brookebroccoli** [Unity-Technologies/Robotics-Nav2-SLAM-Example#22]
Hi there, 

On the info for this tutorial it mentions that this works with docker or ROS2. My environment is configured to ROS1. Will this tutorial work with ROS as well?

Thanks for your time!

**Comment by mrpropellers** [comment]
Hey @brookebroccoli, this example is meant to specifically target ROS2, as it's interfacing with the ROS2 versions of Navigation and the slam_toolbox.  It's likely that you could get it working with ROS, as the Unity-side tools can be converted to ROS with only a few interface changes, but we haven't tested it against the ROS version of the nav stack yet. I should be pushing changes to support ROS/ROS2 hot-swapping to the Unity project in the next few weeks, but we won't have any officially supported analogous ROS environment to run it against. It will still be up to curious users to configure that part themselves.
