### ISSUE TITLE
Docker container not running

### ISSUE THREAD

**Issue by brookebroccoli** [Unity-Technologies/Robotics-Nav2-SLAM-Example#24]
![Screenshot from 2021-09-10 10-53-27](https://user-images.githubusercontent.com/33395020/132781339-c3266fe8-10c7-4ee3-b52c-2cb14d015b12.png)
Hi there,

I'm trying to run the docker container using: docker run -p 6080:80 -p 10000:10000 -p 5005:5005 --shm-size=1024m unity-robotics:nav2-slam-example, however it stays stagnant loading and never loads the docker container (see attached image). Any suggestions as to what to do would be appreciated.

**Comment by brookebroccoli** [comment]
Solved: Once I opened the web browser (http://127.0.0.1:6080), it worked!

**Comment by mrpropellers** [comment]
Great! Yep we don't call out anywhere that the console output from the image doesn't necessarily mean it's not working - some of the messages look mildly alarming but it's all normal and expected.
