### ISSUE TITLE
What OS is recommended for this project

### ISSUE THREAD

**Issue by wilcobonestroo** [Unity-Technologies/Robotics-Nav2-SLAM-Example#30]
Unity and ROS 2 should be able to run on Windows, Mac and Linux. What is the preferred (or tested) setup for this project? E.g. Can I run everything on one Linux machine?

**Comment by mrpropellers** [comment]
We've tested on the latest versions of OS X, Windows 10, and Ubuntu 20.04. You can run everything on one machine with the caveat that the project requires you build the Docker container in the instructions. You can also run everything on a single Linux box without a Docker container, assuming you've got an appropriately configured ROS2 environment to build our Colcon workspace.
