### ISSUE TITLE
LookupError: Could not find the resource 'nav2_bringup' of type 'packages'

### ISSUE THREAD

**Issue by Axin630** [Unity-Technologies/Robotics-Nav2-SLAM-Example#47]
when i try to Start RViz,it said:

[INFO] [launch]: All log files can be found below /home/axin/.ros/log/2022-05-25-06-40-00-383023-axin-vpc-3298
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=InvalidLaunchFileError('py')>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 50, in get_package_prefix
    content, package_prefix = get_resource('packages', package_name)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/resources.py", line 48, in get_resource
    raise LookupError(
LookupError: Could not find the resource 'nav2_bringup' of type 'packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file
    return getattr(launch_file_module, 'generate_launch_description')()
  File "/home/axin/桌面/Robotics-Nav2-SLAM-Example/ros2_docker/colcon_ws/install/unity_slam_example/share/unity_slam_example/unity_slam_example.py", line 31, in generate_launch_description
    os.path.join(get_package_share_directory('nav2_bringup'), 'launch', 'navigation_launch.py')
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 70, in get_package_share_directory
    return os.path.join(get_package_prefix(package_name), 'share', package_name)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 52, in get_package_prefix
    raise PackageNotFoundError(
ament_index_python.packages.PackageNotFoundError: "package 'nav2_bringup' not found, searching: ['/home/axin/桌面/Robotics-Nav2-SLAM-Example/ros2_docker/colcon_ws/install/unity_slam_example', '/home/axin/桌面/Robotics-Nav2-SLAM-Example/ros2_docker/colcon_ws/install/ros_tcp_endpoint', '/opt/ros/foxy']"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 130, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [py]: "package 'nav2_bringup' not found, searching: ['/home/axin/桌面/Robotics-Nav2-SLAM-Example/ros2_docker/colcon_ws/install/unity_slam_example', '/home/axin/桌面/Robotics-Nav2-SLAM-Example/ros2_docker/colcon_ws/install/ros_tcp_endpoint', '/opt/ros/foxy']"

**Comment by nowhereman1999** [comment]
> when i try to Start RViz,it said:
> 
> [INFO] [launch]: All log files can be found below /home/axin/.ros/log/2022-05-25-06-40-00-383023-axin-vpc-3298 [INFO] [launch]: Default logging verbosity is set to INFO Task exception was never retrieved future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=InvalidLaunchFileError('py')> Traceback (most recent call last): File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 50, in get_package_prefix content, package_prefix = get_resource('packages', package_name) File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/resources.py", line 48, in get_resource raise LookupError( LookupError: Could not find the resource 'nav2_bringup' of type 'packages'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file return loader(launch_file_path) File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file return getattr(launch_file_module, 'generate_launch_description')() File "/home/axin/桌面/Robotics-Nav2-SLAM-Example/ros2_docker/colcon_ws/install/unity_slam_example/share/unity_slam_example/unity_slam_example.py", line 31, in generate_launch_description os.path.join(get_package_share_directory('nav2_bringup'), 'launch', 'navigation_launch.py') File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 70, in get_package_share_directory return os.path.join(get_package_prefix(package_name), 'share', package_name) File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 52, in get_package_prefix raise PackageNotFoundError( ament_index_python.packages.PackageNotFoundError: "package 'nav2_bringup' not found, searching: ['/home/axin/桌面/Robotics-Nav2-SLAM-Example/ros2_docker/colcon_ws/install/unity_slam_example', '/home/axin/桌面/Robotics-Nav2-SLAM-Example/ros2_docker/colcon_ws/install/ros_tcp_endpoint', '/opt/ros/foxy']"
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event await self.__process_event(next_event) File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event visit_all_entities_and_collect_futures(entity, self.__context)) File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context) File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context) File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures sub_entities = entity.visit(context) File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit return self.execute(context) File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 130, in execute launch_description = self.__launch_description_source.get_launch_description(context) File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description self._get_launch_description(self.__expanded_location) File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description return get_launch_description_from_any_launch_file(location) File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file raise InvalidLaunchFileError(extension, likely_errors=exceptions) launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [py]: "package 'nav2_bringup' not found, searching: ['/home/axin/桌面/Robotics-Nav2-SLAM-Example/ros2_docker/colcon_ws/install/unity_slam_example', '/home/axin/桌面/Robotics-Nav2-SLAM-Example/ros2_docker/colcon_ws/install/ros_tcp_endpoint', '/opt/ros/foxy']"

Hi，I also get involved with this error，have you solved this error later？If you do，could you please give me some advice？
![image](https://user-images.githubusercontent.com/53631206/208654121-175f4742-6dc3-4cb0-a625-3c17420f5a56.png)

**Comment by wrxsky** [comment]
I came up with the same issue and finally found a solution @Hezhexi2002 . In the Dockfile it seems to be two bugs:

1. By default ros-galactic**-ros-base** will be installed, this does not include nav2-bringup, navigation2 and rviz2, but these packages will be needed.
2.  "RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654" doesn't work probably in Docker.
3. GPG error (solved by https://github.com/Unity-Technologies/Robotics-Nav2-SLAM-Example/issues/49#issuecomment-1198156678)

My environment:
Host: Win 10, Docker Desktop 20.10.21

So i updated the Dockerfile to the following and it works for me:

```
# adapted from: https://github.com/Tiryoh/docker-ros2-desktop-vnc
FROM dorowu/ubuntu-desktop-lxde-vnc:focal
LABEL maintainer="Unity Robotics <unity-robotics@unity3d.com>"

ENV DEBIAN_FRONTEND noninteractive
ENV DEV_NAME=rosdev
ENV ROS_DISTRO=galactic
ENV GROUP_NAME=ros
ENV WS_NAME=colcon_ws

RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -

RUN echo "Set disable_coredump false" >> /etc/sudo.conf
RUN apt-get update -q && \
    apt-get upgrade -yq && \
    apt-get install -yq \
        wget \
        curl \
        git \
        build-essential \
        vim \
        sudo \
        gnupg2 \
        lsb-release \
        locales \
        bash-completion \
        tzdata \
        gosu \
        python3-argcomplete \
        python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Install the immutable components BEFORE we copy in build context stuff to keep the rebuild process manageable
RUN curl http://repo.ros2.org/repos.key | sudo apt-key add -
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
    echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > \
        /etc/apt/sources.list.d/ros2-latest.list && \
    apt-get update -q && \
    apt-get install -y --no-install-recommends \
      ros-${ROS_DISTRO}-desktop \
      python3-rosdep \
      python3-colcon-common-extensions \
      python3-vcstool \
      ros-galactic-navigation2 \
      ros-galactic-nav2-bringup \
    && rm -rf /var/lib/apt/lists/* && rm /etc/apt/sources.list.d/ros2-latest.list

RUN useradd --create-home --home-dir /home/${DEV_NAME} --shell /bin/bash --user-group --groups adm,sudo ${DEV_NAME} && \
    echo "$DEV_NAME:$DEV_NAME" | chpasswd && \
    echo "$DEV_NAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
COPY --chown=${DEV_NAME} colcon_ws /home/${DEV_NAME}/colcon_ws
COPY ros2-setup.bash /bin/ros2-setup.bash
# Doing a second fetch of sources & apt-get update here, because these ones depend on the state of the build context
# in our repo
RUN curl http://repo.ros2.org/repos.key | sudo apt-key add -
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
    echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > \
        /etc/apt/sources.list.d/ros2-latest.list && \
    apt-get update -q && \
    rosdep init && \
    chmod +x /bin/ros2-setup.bash && \
    gosu ${DEV_NAME} /bin/ros2-setup.bash && \
    runuser -u ${DEV_NAME} ros2-setup.bash && \
    rm /bin/ros2-setup.bash && \
    rm -rf /var/lib/apt/lists/* && rm /etc/apt/sources.list.d/ros2-latest.list

RUN echo ". /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/${DEV_NAME}/.bashrc && \
    echo ". /home/${DEV_NAME}/${WS_NAME}/install/local_setup.bash" >> /home/${DEV_NAME}/.bashrc

ENV TURTLEBOT3_MODEL=waffle_pi

# To bring up tb3 simulation example (from https://navigation.ros.org/tutorials/docs/navigation2_with_slam.html)
# cd catkin_ws && source install/setup.bash && ros2 launch nav2_bringup tb3_simulation_launch.py slam:=True

# Informs the environment that the default user is not root, but instead DEV_NAME
ENV USER ${DEV_NAME}
```
Changes:

- 11 adding "RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -"
- 34 and 55 adding apt-key for ros2
- 40 44 45 installing ros2-desktop with nav2 and rviz

**Comment by nowhereman1999** [comment]
> I came up with the same issue and finally found a solution @Hezhexi2002 . In the Dockfile it seems to be two bugs:
> 
> 1. By default ros-galactic**-ros-base** will be installed, this does not include nav2-bringup, navigation2 and rviz2, but these packages will be needed.
> 2. "RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654" doesn't work probably in Docker.
> 3. GPG error (solved by [docker build runs into GPG error #49 (comment)](https://github.com/Unity-Technologies/Robotics-Nav2-SLAM-Example/issues/49#issuecomment-1198156678))
> 
> My environment: Host: Win 10, Docker Desktop 20.10.21
> 
> So i updated the Dockerfile to the following and it works for me:
> 
> ```
> # adapted from: https://github.com/Tiryoh/docker-ros2-desktop-vnc
> FROM dorowu/ubuntu-desktop-lxde-vnc:focal
> LABEL maintainer="Unity Robotics <unity-robotics@unity3d.com>"
> 
> ENV DEBIAN_FRONTEND noninteractive
> ENV DEV_NAME=rosdev
> ENV ROS_DISTRO=galactic
> ENV GROUP_NAME=ros
> ENV WS_NAME=colcon_ws
> 
> RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
> 
> RUN echo "Set disable_coredump false" >> /etc/sudo.conf
> RUN apt-get update -q && \
>     apt-get upgrade -yq && \
>     apt-get install -yq \
>         wget \
>         curl \
>         git \
>         build-essential \
>         vim \
>         sudo \
>         gnupg2 \
>         lsb-release \
>         locales \
>         bash-completion \
>         tzdata \
>         gosu \
>         python3-argcomplete \
>         python3-pip \
>     && rm -rf /var/lib/apt/lists/*
> 
> # Install the immutable components BEFORE we copy in build context stuff to keep the rebuild process manageable
> RUN curl http://repo.ros2.org/repos.key | sudo apt-key add -
> RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
>     echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > \
>         /etc/apt/sources.list.d/ros2-latest.list && \
>     apt-get update -q && \
>     apt-get install -y --no-install-recommends \
>       ros-${ROS_DISTRO}-desktop \
>       python3-rosdep \
>       python3-colcon-common-extensions \
>       python3-vcstool \
>       ros-galactic-navigation2 \
>       ros-galactic-nav2-bringup \
>     && rm -rf /var/lib/apt/lists/* && rm /etc/apt/sources.list.d/ros2-latest.list
> 
> RUN useradd --create-home --home-dir /home/${DEV_NAME} --shell /bin/bash --user-group --groups adm,sudo ${DEV_NAME} && \
>     echo "$DEV_NAME:$DEV_NAME" | chpasswd && \
>     echo "$DEV_NAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
> COPY --chown=${DEV_NAME} colcon_ws /home/${DEV_NAME}/colcon_ws
> COPY ros2-setup.bash /bin/ros2-setup.bash
> # Doing a second fetch of sources & apt-get update here, because these ones depend on the state of the build context
> # in our repo
> RUN curl http://repo.ros2.org/repos.key | sudo apt-key add -
> RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
>     echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > \
>         /etc/apt/sources.list.d/ros2-latest.list && \
>     apt-get update -q && \
>     rosdep init && \
>     chmod +x /bin/ros2-setup.bash && \
>     gosu ${DEV_NAME} /bin/ros2-setup.bash && \
>     runuser -u ${DEV_NAME} ros2-setup.bash && \
>     rm /bin/ros2-setup.bash && \
>     rm -rf /var/lib/apt/lists/* && rm /etc/apt/sources.list.d/ros2-latest.list
> 
> RUN echo ". /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/${DEV_NAME}/.bashrc && \
>     echo ". /home/${DEV_NAME}/${WS_NAME}/install/local_setup.bash" >> /home/${DEV_NAME}/.bashrc
> 
> ENV TURTLEBOT3_MODEL=waffle_pi
> 
> # To bring up tb3 simulation example (from https://navigation.ros.org/tutorials/docs/navigation2_with_slam.html)
> # cd catkin_ws && source install/setup.bash && ros2 launch nav2_bringup tb3_simulation_launch.py slam:=True
> 
> # Informs the environment that the default user is not root, but instead DEV_NAME
> ENV USER ${DEV_NAME}
> ```
> 
> Changes:
> 
> * 11 adding "RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -"
> * 34 and 55 adding apt-key for ros2
> * 40 44 45 installing ros2-desktop with nav2 and rviz

Thank you for your detailed reply,actually the 3 bugs you mentioned above I I have also encountered too at first.For the gpg error,I did follow the [docker build runs into GPG error](https://github.com/Unity-Technologies/Robotics-Nav2-SLAM-Example/issues/49#issuecomment-1198156678) and solve it.Besides,I also change the source.list into the tuna mirror due to the       Failed to fetch error in the building process and here is my full Dockerfile [Dockerfile.txt](https://github.com/Unity-Technologies/Robotics-Nav2-SLAM-Example/files/10273998/Dockerfile.txt).Anyway,I will try the solution you have proposed and give you more feedback later.But in the end, allow me to ask you one more question,have you also meet this situation #57 when you open the SimpleWarehouseScene in the Editor？If so,could you please give me relevant suggestions？I would be very grateful!

**Comment by wrxsky** [comment]
> 
@Hezhexi2002 The third change "40 44 45 installing ros2-desktop with nav2 and rviz" should be the key to fix this issue.
No, i didn't. I suggest you try different graphics settings.

**Comment by nowhereman1999** [comment]
> > 
> 
> @Hezhexi2002 The third change "40 44 45 installing ros2-desktop with nav2 and rviz" should be the key to fix this issue. No, i didn't. I suggest you try different graphics settings.

Yes, I used the Dockerfile you provided directly, just replaced source.list with tuna mirror because it will occur an error like below if I doesn't change the source:
![image](https://user-images.githubusercontent.com/53631206/208883884-7e803a88-8ed5-4b07-9346-9fac5e588155.png)
but I still got the Failed to fetch error like this after I change the source:
![image](https://user-images.githubusercontent.com/53631206/208888326-dc90c999-183d-4647-b90a-1993543a0ac1.png)
I don't know how the build was successful last time. It seems that I tried a few times after turning off the proxy, but this time no matter whether I turn off the proxyor not, the error still exits.And for https://github.com/Unity-Technologies/Robotics-Nav2-SLAM-Example/issues/57,I didn't change any graphics settings when I open the project,I don't konw why it become green,maybe I really need to change some configurations of the project.Anywway,thank you for your patient reply again,I will keep searching on google to see if there is any solution:-)

**Comment by kimbring2** [comment]
@Hezhexi2002 @wrxsky I had the same problem in Docker. Therefore, I install ROS2 in my locally and can run the example well.

**Comment by AliH17** [comment]
@Hezhexi2002 @wrxsky could you send the working docker file

**Comment by AliH17** [comment]
> [@Hezhexi2002](https://github.com/Hezhexi2002) [@wrxsky](https://github.com/wrxsky) I had the same problem in Docker. Therefore, I install ROS2 in my locally and can run the example well.

@kimbring2 could you send me a guide on how you did that?
