### ISSUE TITLE
How to edit the params of ROS2 Navigation

### ISSUE THREAD

**Issue by Xposeder** [Unity-Technologies/Robotics-Nav2-SLAM-Example#60]
I add a dynamic obstacle which will be moved when mouse is clicked on the ground. However, the global costmap will not be fresh correctly when the obstacle was moved. The old costmap will be still there for a long time. 
![1](https://user-images.githubusercontent.com/72307252/216221567-8914c58d-f432-48c5-a962-37c51729c332.gif)
I followed the nav2 package introduction to edit the param of global costmap and rerun "colon build", it doesn't work. So I want to know how to edit the params of ROS2 Navigation properly.

**Comment by prakash-aryan** [comment]
Hey @Xposeder were you able to fix this issue?

**Comment by Xposeder** [comment]
> Hey @Xposeder were you able to fix this issue?

sorry, I don't use it anymore.
